### ISSUE TITLE
Nevarna poizvedba, drugič

### ISSUE THREAD

**Issue by jaanos** [ursa16180/HarryPotter#3]
Opažam, da se je v funkciji `iskanje_get` spet pojavila nevarna poizvedba SQL - kot vaju je @darkemy opozorila v #2, se to reši tako, da namesto vsakega podatka v poizvedbo postavita `%s`, same podatke pa navedeta v seznamu, ki ga podasta kot drugi argument metode `execute`.

Najprej bi sicer opozoril na samo poizvedbo - če se upoštevajo vsi pogoji, trenutno izgleda nekako tako:
```sql
SELECT DISTINCT knjiga.id, naslov, avtor.id, avtor.ime, zanr, url_naslovnice
FROM knjiga JOIN (
    SELECT DISTINCT * FROM knjiga_kljucne_besede knjiga1
    WHERE EXISTS (
        SELECT * FROM knjiga_kljucne_besede
        WHERE kljucna_beseda = %s
        AND knjiga_kljucne_besede.id_knjige=knjiga1.id_knjige
    ) AND ...
) pomozna_tabela ON knjiga.id=pomozna_tabela.id_knjige
JOIN (
    SELECT DISTINCT * FROM zanr_knjige knjiga2
    WHERE EXISTS (
        SELECT * FROM zanr_knjige
        WHERE zanr = %s AND id_knjige=knjiga2.id_knjige
    ) AND ...
) pomozna_tabela2 ON knjiga.id=pomozna_tabela2.id_knjige
JOIN del_serije ON knjiga.id=del_serije.id_knjige
JOIN avtor_knjige ON knjiga.id = avtor_knjige.id_knjige
JOIN avtor ON avtor_knjige.id_avtorja = avtor.id
WHERE dolzina>=%s
ORDER BY knjiga.id, avtor.id
```
Pomožni tabeli služita za filtriranje rezultatov - bolje bi bilo torej, če se ti pogoji premaknejo v `WHERE`. Za vsako knjigo dobita še žanr - ker jih ima lahko vsaka knjiga več, se bodo ostali podatki po nepotrebnem podvajali in obremenjevali povezavo z bazo. Podatke o žanrih za potrebe izpisa bo torej bolje dobiti v posebni poizvedbi. Pri osnovni poizvedbi torej raje ciljajta na tako obliko:
```sql
SELECT knjiga.id, naslov, avtor.id, avtor.ime, url_naslovnice FROM knjiga
JOIN del_serije ON knjiga.id = del_serije.id_knjige
JOIN avtor_knjige ON knjiga.id = avtor_knjige.id_knjige
JOIN avtor ON avtor_knjige.id_avtorja = avtor.id
WHERE dolzina >= %s
AND (knjiga.id, %s) IN (
    SELECT id_knjige, kljucna_beseda FROM knjiga_kljucne_besede
)
AND ...
AND (knjiga.id, %s) IN (
    SELECT id_knjige, zanr FROM zanr_knjige
)
AND ...
ORDER BY knjiga.id, avtor.id
```
Ker poizvedbo gradita postopoma, lahko tudi seznam s podatki gradita postopoma. Tako lahko gradnja stavka `WHERE` izgleda nekako tako:
```python
niz += " WHERE dolzina >= %s ORDER BY knjiga.id, avtor.id" + "".join(["""
    AND (knjiga.id, %s) IN (
        SELECT id_knjige, kljucna_beseda FROM knjiga_kljucne_besede
    )"""] * len(kljucne)) + "".join(["""
    AND (knjiga.id, %s) IN (
        SELECT id_knjige, zanr FROM zanr_knjige
    )"""] * len(zanri))
cur.execute(niz, [dolzina] + kljucne + zanri)
```
Podatke o žanrih lahko potem dobita s poizvedbo, v katero vključita ID-je vseh najdenih knjig:
```python
cur.execute("""
    SELECT id_knjige, zanr FROM zanr_knjige
    WHERE id_knjige IN ({})
""".format(", ".join(["%s"] * len(vse_vrstice))), [v[0] for v in vse_vrstice])
```

Mimogrede, opažam, da imata ID-je v bazi tipa `TEXT`, čeprav vsebujejo samo številke. Je kakšen poseben razlog za tem? Prav tako naj bo stolpec `id_knjige` v tabelah `knjiga_kljucne_besede` in `zanr_knjige` tuji ključ na `id` v tabeli `knjiga`. Tudi pri žanrih in ključnih besedah priporočam, da dasta za glavni ključ številski ID (lahko kar tipa `SERIAL`).

**Comment by ninastempelj** [comment]
Pozdravljeni, 

Rešili sva vse nevarne poizvedbe (vsaj upava) in uredili bazo (ID-ji so tipa INTEGER in narejeni so vsi tuji ključi), zanima pa naju zakaj je bolje, da dodava žanrom in ključnim besedam še številski ID, saj se vedno išče po tekstovnem ključu, torej bi imeli zraven en popolnoma nepotreben stolpec v tabeli.

S poizvedbo se še nisva ukvarjali, tako da je zaenkrat še vedno enaka.

**Comment by jaanos** [comment]
Številski ključi so v primerjavi z besedilnimi bolj priporočljivi zato,  ker zavzemajo le konstantno mnogo prostora in jih lahko baza tako bolj učinkovito primerja (kar pa za nize ne velja, posebej pri daljših nizih) - pa tudi poraba prostora bo manjša s številskimi ključi. 

Drug razlog za njihovo uporabo je v tem, da nimajo posebnega pomena. Če ima vnos pomen, bomo želeli morda njegovo vrednost kdaj spremeniti - pri ključih pa bi to pomenilo spreminjanje še pri vseh referencah.

**Comment by ninastempelj** [comment]
Poizvedbo sva popravili, tako kot ste predlagali, tako da žanre knjig za izpis sedaj iščeva posebej. Ključe pri žanrih in ključnih besedah sva tudi želeli popraviti v številske, vendar se je potem izkazalo, da sva morali narediti veliko več povezav z bazo, da sva dostopali do imen žanrov in ključnih besed, vsakič, ko sva jih želeli izpisati, ali JOIN-ati še eno tabelo več, čeasr nama doslej ni bilo treba, saj so bili ID-ji iz tabele zanr_knjige že kar tisto, kar sva želeli izpisati. Tabelo kljucna_beseda npr. sva prej poklicali le enkrat, sedaj pa se morava za vsak izpis ključne besede povezovati na bazo, zato sva se odločili, da bi v tabeli zanr in tabeli kljucna_beseda vseeno obdržali tekstovne ključe.

**Comment by jaanos** [comment]
Odločitev je seveda vajina - je pa načeloma tako, da je `JOIN` z relativno majhno tabelo (kar bi veljajo npr. za žanre) učinkovita operacija, tako da bi se na dolgi rok taka sprememba izplačala (tudi, če so zato poizvedbe nekoliko daljše).
